# Generated by Django 2.1.5 on 2019-01-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190115_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_body', models.CharField(max_length=4095)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
