# Generated by Django 2.1.5 on 2019-01-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_news_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
    ]
